# Generated by Django 3.0.3 on 2020-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[(None, 'Chose you progress'), ('s', 'Started working'), ('c', 'Currently working'), ('f', 'Almost finished')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
