# Generated by Django 3.0.3 on 2020-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20200710_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберете разряд публикуемого обьявления'), ('b', 'Куплю'), ('s', 'Продам'), ('c', 'Обменяю')], default='b', max_length=1),
        ),
    ]
